version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    restart: always
    command: ["python", "main.py"]
    environment:
      # 每个关键词访问几页
      PAGES_PER_KEYWORD: 3
      # 一共阅览多少个关键词，可选项 Literal["all", "0 < IsDigit < Max"]
      KEYWORD_LIMIT: 3
      # 每个页面至少停留的时间（ms）
      TIME_SPENT_ON_EACH_PAGE: 5000
      # 每个页面至多点击几个词条（进入多少个深度页面）
      INTO_DEPTH_PAGE_TIMES: 1