version: '3.7'
services:
  wh-seo:
    image: ech0sec/wh-seo:latest
    volumes:
      - ./tmp_dir:/home/wh-seo/tmp_dir
    restart: always
    command: ["python3", "timer.py"]
    environment:
      LONG_TAIL_WORDS: 进化论资产
      LOOP_THE_KEYWORD: 进化论资产超额收益
      LOOP_LIMIT: 10
      END_DAYS: 7
      INTERVAL_SECONDS: 600