version: '3.7'
services:
  wh-seo:
    image: ech0sec/wh-seo:latest
    volumes:
      - ./keywords.txt:/home/wh-seo/keywords.txt
      - ./tmp_dir:/home/wh-seo/tmp_dir
    restart: always
    command: ["python3", "timer.py"]
    environment:
      # 每个关键词访问几页
      PAGES_PER_KEYWORD: 2
      # 一共阅览多少个关键词，可选项 Literal["all", "0 < IsDigit < Max"]
      KEYWORD_LIMIT: 5
      # 每个页面至少停留的时间（ms）
      TIME_SPENT_ON_EACH_PAGE: 6000
      # 每个页面至多点击几个词条（进入多少个深度页面）
      INTO_DEPTH_PAGE_TIMES: 2
      # 轮动词条
      # TUMBLE_RELATED_KEYWORD: 进化论资产
      #  是否录频，取消注释则录制
      # ENABLE_RECORD_VIDEO: 1
      # 添加额外的黑名单关键词 英文半角逗号分隔 "," 不需要空格
      # BLACKLIST_CONTENT:
      # LOOP_THE_KEYWORD: 进化论资产面试
      # LOOP_LIMIT: 10
      # INTERVAL_SECONDS: 300
      # SEARCH_KEYWORDS: 进化论一平