name: WhiteList SEO

on:
  workflow_dispatch:

  # https://crontab.guru/
  schedule:
    - cron: "*/20 * * * *"

jobs:
  setup:
    strategy:
      matrix:
        instance: [ 1, 2, 3, 4, 5 ]
    env:
      LONG_TAIL_WORDS: 进化论资产
      LOOP_THE_KEYWORD: 进化论资产科学投资
      LOOP_LIMIT: 10
      FAKE_HASH: "Automated deployment @ $(date '+%Y-%m-%d %H:%M:%S') Asia/Shanghai"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout environment
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: 'pip'
      - name: 安装依赖+运行脚本
        continue-on-error: true
        timeout-minutes: 10
        run: |
          pip install -U playwright loguru python-dotenv 
          playwright install chromium --with-deps
          sudo timedatectl set-timezone "Asia/Shanghai"
          python main.py
