name: WhiteList SEO

on:
  workflow_dispatch:

  # https://crontab.guru/
  schedule:
    - cron: "*/20 * * * *"

jobs:
  setup:
    strategy:
      matrix:
        instance: [ 1, 2, 3, 4, 5 ]
    env:
      # 每个关键词访问几页
      # PAGES_PER_KEYWORD: 2
      # 一共阅览多少个关键词，可选项 Literal["all", "0 < IsDigit < Max"]
      KEYWORD_LIMIT: all
      # 每个页面至少停留的时间（ms）
      # TIME_SPENT_ON_EACH_PAGE: 6000
      # 每个页面至多点击几个词条（进入多少个深度页面）
      # INTO_DEPTH_PAGE_TIMES: 2
      # 覆盖掉 keywords.txt 优先级更高的检索词列表，以英文半角逗号分开，不需要空格
      # SEARCH_KEYWORDS: 进化论资产面试
      # LOOP_THE_KEYWORD: 进化论资产科学投资
      # LOOP_LIMIT: 6
      # TUMBLE_RELATED_KEYWORD: 进化论一平
      PREFIX_KW: 进化论资产
      FAKE_HASH: "Automated deployment @ $(date '+%Y-%m-%d %H:%M:%S') Asia/Shanghai"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout environment
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: 'pip'
      - name: 安装依赖+运行脚本
        continue-on-error: true
        timeout-minutes: 10
        run: |
          pip install -U playwright loguru python-dotenv 
          playwright install chromium --with-deps
          sudo timedatectl set-timezone "Asia/Shanghai"
          python main.py
