name: WhiteList SEO

on:
  workflow_dispatch:

  # https://crontab.guru/
  schedule:
    - cron: "*/20 * * * *"

jobs:
  setup:
    env:
      # 每个关键词访问几页
      PAGES_PER_KEYWORD: 3
      # 一共阅览多少个关键词，可选项 Literal["all", "0 < IsDigit < Max"]
      KEYWORD_LIMIT: 3
      # 每个页面至少停留的时间（ms）
      TIME_SPENT_ON_EACH_PAGE: 5000
      # 每个页面至多点击几个词条（进入多少个深度页面）
      INTO_DEPTH_PAGE_TIMES: 1
      FAKE_HASH: "Automated deployment @ $(date '+%Y-%m-%d %H:%M:%S') Asia/Shanghai"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout environment
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: 'pip'
      - name: 运行脚本
        continue-on-error: true
        timeout-minutes: 3
        run: |
          pip install -U playwright loguru python-dotenv 
          playwright install chromium --with-deps
          sudo timedatectl set-timezone "Asia/Shanghai"
          python main.py
      - name: 上传会话缓存
        continue-on-error: true
        run: |
          echo "${{ env.FAKE_HASH }}" > _token
          git add .
          git commit -m "${{ env.FAKE_HASH }}" 
          git push -f
